### ISSUE TITLE
Konstansok Posch

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#108]
Lehet, h nem emléxem jól, de itt mintha 1,12 vagy 1,15 lett volna a váltó szám... vagy nem? Ez így baromira kevés és magunkat vágjuk át. Minden 10 legyártott Posch után 1m3 fával többet használunk el a valóságban. A program meg azt mondaná, hogy van még 1m3 fa, amiből tudunk még 1 Posch-t csinálni. A Poschban kb. annyi fa van mint az "Egyutas normál kaloda"-ban.

**Comment by koch-mate** [comment]
Nem tart semeddig atirni, mi legyen az uj ertek? Ez viszont csak a jovoben felvett megrendelesekre lesz hatassal.

**Comment by ihartu** [comment]
Ok, a Posch (hálós és hálós fóliázott) 1,17m3 legyen. Köszi, CL.
