### ISSUE TITLE
0 arral utolag felvett tetel

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#111]
utólag vittem be a fenyő megrendeléseket, elfelejtettem az árakat bevinni. Lehet utólag pótolni? Ha nem, akkor ne engedjen utólag kiegészítő tételeket bevinni úgy, h nem töltünk ki minden ablakot. CL.

**Comment by koch-mate** [comment]
Utolag nem lehet szerkeszteni, de ha megirod, hogy mi lenne az ertek, akkor beleirom az adatbazisban. 

Azt, hogy ne engedjen ilyet legkozelebb, majd megcsinalom.
