### ISSUE TITLE
Konstansok "Posch"

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#112]
Így nem jó. Csak a tömör m3-t kellett volna átírni.
A csomagolási egységben marad a szórt ürméter.    2,34szűrm.

**Comment by koch-mate** [comment]
Azt nem tudom megcsinalni, mert akkor valtoztatni kell a mertekegysegek kozti atvaltast, es akkor minden mas is valtozni fog. Ez nem gond?

**Comment by ihartu** [comment]
sztem ez így gond. nézz rá a táblázatra. mindenhol rűrm és szűrm van, csak a poschnál írtál m3-t. ahol eddig szűrm volt és ha jól emléxem akkor 2,1.
Egy csomagolási egységben lévő mennyiség az vagy szűrm vagy rűrm. Nem lehet m3.
Vagy nem tudom elmagyarázni amit szeretnék.

**Comment by koch-mate** [comment]
Az mindegy, hogy milyen mertekegysegben van megadva 1-1 csomagolas tipus, mert a mertekegysegek kozott fix az atszamitas, 1 tomor kobmeter fa mindig ugyanannyi rakott urmeternek fog megfelelni, csomagolastipustol fuggoen. Most atallitottam, hogy szort urmeter legyen az alap mennyiseg, de ettol a szamok nem valtoztak. Ha igy nem jo, akkor a mertekegyseg-atvaltasokat kene atgondolni meg egyszer, de az minden mas csomagolastipust is erinteni fog.
