### ISSUE TITLE
ID912 Alapanyag levétel hiánya!

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#114]
nem veszi le az alapanyagot. 3x próbáltam. az eseménynaplóban (8293-tól) végig lehet követni. kiválasztom a mennyiséget, leokézom, de nem veszi le az alapanyagot.

**Comment by ihartu** [comment]
viszont a csomagolóanyagot duplán veszi le!

**Comment by koch-mate** [comment]
Megtalaltam a hibat, es ki is javitottam. A naplo alapjan bevittem a gyartando teteleket, es el is fogadta. A tobbszori csomagoloanyag levonas azert volt, mert tobbszor kerult at legyarott allapotba. Az osszes feleslegeset kitoroltem a Csomagoloanyag > Keszletmozgas alatt.
