### ISSUE TITLE
Régi admin Karcsi bánata

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#115]
Hiányol 2 dolgot: A régi adminban a "Lekérdezések"-nél van két ablak: Beszállítók és a Vevők. Ezt a látványt és tartalmat szeretné látni az új programban a "Kimutatás"-oknál. Adott vevőnek hány kamionnyi megrendelése van, abból mi teljesült már, a megrendelt x kamionnak mennyi az értéke stb. "Megrendelő szerinti kimutatás - Export megrendelések" m3-ben vannak megadva, ami ok, de itt 
nem látni, hogy mi teljesült és mi nem. De ezzel kapcsolatban jobb lenne ha a Zsolttal vennéd fel a kapcsolatot.

**Comment by koch-mate** [comment]
Tudnatok kuldeni egy mintat arrol, hogy hogy nezzen ki pontosan? Mondjuk egy Excel fileban, de lehet akar papiron is.

**Comment by ihartu** [comment]
Ezt én nem vállalom. Igazság szerint nem tudom, h mit szeretne. A régi adminban, az a két táblázat nem mond neked semmit? Vmi olyat szeretne, de mégsem....
A péntekről még nem tudok semmit.
