### ISSUE TITLE
ID.1010

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#129]
Hello Máté, rég találkoztunk. 
A Karcsi jelentkezett nálam egy problémával.
Példának hoztam az ID.1010-et.
Az adatok a megrendelésben (mennyiség, ár, fuvar stb) jól vannak feltüntetve.
Viszont a Kimutatások/Megrendelések havi nézetében, augusztus hónapban az ID.1010-nél az ár teljesen értelmezhetetlen. Szinte mindegyik export megrendelésnél az összeg nem helyes.

**Comment by koch-mate** [comment]
Szia! Csak az ar mezo rossz, vagy mashol is talaltatok hibat?

**Comment by ihartu** [comment]
Nem tudom, ezt a táblázatot a karcsi "használja". Csak az az érdekes, hogy ez csak tegnap jött elő neki....

**Comment by ihartu** [comment]
Karcsi*
