### ISSUE TITLE
Export megrendelés

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#13]
nem jó, hogy a megrendelés bevitele közben (hozzáadás a megrendeléshez után) nem lehet módosítani, hanem csak törölni. ha valamit elírok 1 tételben akkor az egészet törölni kell és kezdhetem az egészet elölről. ha a fa hosszát rosszul állítom be, de a többi adat jó akkor ne kelljen 1 tételsort törölni.

**Comment by koch-mate** [comment]
nem kell, mert amikor hozzaadsz egy tetelsort, akkor minden beallitas megmarad, es ujra ugyanazt hozza tudod adni, vagy modositani 1 adatot, es minden mast ugyanugy hagyni.
