### ISSUE TITLE
Export fuvar

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#14]
Export rendelés bevitele. Ilyenkor még nem tudom mennyi lesz a fuvar. Ha nullát vagy bármennyit beírok, tudom később módosítani? Akár ha már gyártás közben van a fa.

**Comment by koch-mate** [comment]
Beallitottam, hogy az export megrendelesnel a fuvardijat ne legyen kotelezo kitolteni.

**Comment by koch-mate** [comment]
Kesz, a fuvardijra kattintva utolag at lehet irni. Jelenleg akar lezart rendeles eseten is.
