### ISSUE TITLE
megrendelés státusz

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#15]
legyen egy "gyártás alatt" és a várakozik az vonatkozzon a szállításra : "szállításra kész".
és lehetne egy " gyártásra betervezve". szerintem.
Így meg lenne minden fázis:
Feldolgozás alatt - Elfogadva - Gyártásra betervezve - Gyártás alatt - Szállításra kész - Teljesítve - Visszautasítva - Visszamondott.
Szerinted?
Úgy gondolom, h én beviszem a megrendelést és el is fogadom. A telepvezető gyártásra betervezi, gyártás alatt-ra is ő állítja át, és a végén jelzi, hogy szállításra kész. majd jövök én, hogy teljesítve, ha elküldtem a kamiont.
Addig amíg nincs gyártás alatt, lehessen a megrendelésen módosítani. ne csak törölni lehessen.

**Comment by koch-mate** [comment]
ez most is gyakorlatilag pont igy van, csak tetelenkent. a "Varakozik" statuszt kivettem, igy most a kovetkezo a menet: 
Feldolgozas alatt - Elfogadva 
itt megkapja a telep, de neki tetelenkent kell visszaigazolnia, egy kozos statusz nem fejezi ki azt, ha pl 2 bukk tetelt betervez, de 1 korist meg nem, mert abbol nincs anyag: 
Visszaigazolasra var - Gyartasra var - Legyartva
Ha minden tetel elkeszul, akkor pedig atkerul
Szallitasra var statuszra, ami utan Teljesitve lesz.
Emellett barmikor lehet visszamondott es visszautasitott.
