### ISSUE TITLE
Fuvar

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#16]
Lehessen módosítani. 
De most észrevettem egy (talán) fontosabb dolgot. Mi az export árainkat fuvarral együtt (adjuk meg a vevőnek) használjuk. Az ár (pl. kalodánkeént 74euró) tartalmazza a fuvart is. Amikor a végösszeghez hozzáadom a fuvar (600euro) árat, nem a valós összeget mutatja. Mert az én áram tartalmazza már a fuvar árat.
Mivel mi így dolgozunk, ezen nem kellene változtatni. De így nincs értelme a fuvar árnak. 
Szerintem csak mutassa megrendelésenként, de ne kalkulálja bele az árba.

**Comment by koch-mate** [comment]
Ennek elvben nincs akadalya, csak ki kell vennem, hogy osszeadja, de nagyon nem javaslom az alabbiak miatt:
 - a lakossaginal nem igy van, igy nem konzisztens
 - ha kesobb barmilyen reportot szeretnenk csinalni az export megrendelesek faanyag arabol, arra nem lesz lehetosegunk, mert a program nem fogja tudni, hogy a beirt tetelarnak mekkora resze a fuvar es mekkora a faanyag tenyleges koltsege (gondolom mas a fuvardij, ha a Ausztria innenso felebe viszitek vagy Sziciliaba viszitek ugyanazt az arut)

Ezert ezt most nem csinaltam meg meg, kerlek gondold at, hosszu tavon sokkal jobb lenne, ha kulon tudnad beirni es kulon mentenenk el a faanyag arat, es a fuvardijat, ugy, ahogy most van.
