### ISSUE TITLE
Export igért teljesítési határidő

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#2]
Jó lenne ha hétben lenne megadva az ígért teljesítési határidő

**Comment by koch-mate** [comment]
Azert sokkal jobb napokat hasznalni, mert a hetek nem esnek altalaban egybe a honapokkal (nem minden honap hetfon kezdodik), es ezert az osszes kimutatas, amit havi bontasban kertek le, rossz adatokat fog mutatni. (emellett mas okai is vannak, ami miatt celszeru a napot megtartani, pl igy kesobb lehet majd olyat is mondani, hogy a gyartasi ido csak 10 vagy 5 nap, a szallitas meg csak 2 nap, ezt hetekkel szinten nem lehetne.)

Annyit csinaltam most, hogy az osszes datumvalaszto kiirja a sorok elejen a hetek szorszamat is, igy mindig latni fogod, es javaslom, hogy akkor minden eseben, ha csak a het a lenyeg, hetfot valassz ki.
