### ISSUE TITLE
Szállításra váró tételek

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#21]
Itt látható az export és a lakossági egyszerre? Ha igen, lehet szűrni, h csak az egyik vagy a másikat lássam?
Aki a lakossági szállítással foglalkozik, látja az export szállítást is?

**Comment by koch-mate** [comment]
Igen, mindketto latszik. Szurni nem lehet, de tudja rendezni, hogy elol mutassa az ossze lakossagit, alatta az osszes exportot, vagy forditva. Ha kell, nem nagy munka megcsinalni, hogy legyen kulon oldal a lakossagi, es kulon az export szallitasoknak.

**Comment by ihartu** [comment]
Igen, legyen külön a lakossági és az export szállítás. Én nem szeretném látni a lakosságit, a "lakossági" kollégának meg ne zavarjon be az export.
