### ISSUE TITLE
Gyártás, szükséges alapanyag felhasználás 1.)

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#24]
1.)Gyártásnál, a szükséges alapanyag (m3) felhasználás megadásánál ne kelljen a lap aljáig görgetni, ha van egy csomó szállítólevél bevitel. mert mindig a legfelső sorból veszi le a szükséges m3-t. legyen fent is egy "enter" gomb. 

2.)Pénteken Zsolttal azt vettük észre, ha pl. az első sorban van 2m3, a másodikban 14,3m3 és mi lefogyasszuk ezt a két sort és amikor visszatérünk egy új tétel bevitelekor akkor ott vannak még mindig az előző mennyiségek és újból le lehet belőlük venni a felhasznált mennyiséget. Pedig ezeknek már el kellett volna "tünniük".

**Comment by koch-mate** [comment]
1.) Hozzaadtam egy Mentes gombot felul is.

2.) Ezt javitottam a #38 kapcsan.

Kerlek, egy ticketbe csak egy kerest irjatok, hogy egyertelmu legyen, es ha az megvan, akkor le tudjuk zarni. Cserebe, ha ugyanazzal a temaval mas gond vagy megjegyzes is van, arra kerlek ne nyissatok uj ticketet, hanem irjatok a meglevo ala, hogy aztan egy helyen lassuk az egesz temahoz tartozo megbeszelest. Koszonom! :)
