### ISSUE TITLE
Export rendelés teljesítés

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#25]
Ne lehessen úgy lezárni egy export rendelést, h a szállítás nincs lezárva. teljesítve, de nincs kipipálva a fuvar.

**Comment by koch-mate** [comment]
Megcsinaltam, most nem lehet "Teljesitve" statuszra allitani, amig nem szallitjak le. Ha leszallitjak, akkor automatikusan teljesitett lesz.
