### ISSUE TITLE
Megrendelés ablak

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#28]
a megrendelés ablak lenyitásakor legyen külön az export és a lakossági megrendelések. ne kelljen mindig szűrögetni.

**Comment by koch-mate** [comment]
Kesz, lett kulon egy lakossagi rendeleseket szuro "Felvett megrendelesek listaja", amit a lakossagi ugyintezo is lat. Itt modositani is lehet.

Az export alatt pedig lett egy "Felvett megrendelesek kezelese", amit az export ugyintezo lathat, es itt modositani/torolni is tud.
