### ISSUE TITLE
Export rendelés bevitel, csomagolás

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#29]
Ne sorok legyenek, hanem egy legördülő ablak ahol kiválasztom a megfelelő csomagolást. Mellette egy + jel, ha plussz tételt szeretnék bevinni.
Nagyon sokat kell görgetni egy rendelés beviteléhez.

**Comment by koch-mate** [comment]
Erre szivesen adok ajanlatot, de eloszor kerlek jussunk tul a tesztuzemen.

**Comment by koch-mate** [comment]
C: "Sajnos a fenti felvetésre nem emléxem. Illetve vmi rémlik, de hagyjuk! Tényleg."
