### ISSUE TITLE
Export rendelés bevitele

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#3]
Rendelés bevitelekor nem szorozza fel a végösszeget a bevitt mennyiséggel (22x144 + 1x72 az neki 261.

**Comment by koch-mate** [comment]
Azert, mert az nem egysegar, hanem teljes ar - ezt a multkor pont megbeszeltuk, hogy a lakossaginal szamoljon egysegar alapjan, itt viszont te ird be kezzel. Megsem igy szeretnetek?

**Comment by ihartu** [comment]
és ebben is igazad van! sorry.
