### ISSUE TITLE
Export megrendelő (Zsolt)

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#31]
Export megrendelő nem létezik (csak magában van). A gombhoz nincs funkció rendelve.

**Comment by koch-mate** [comment]
Ezt nem ertem, hol van ez, melyik oldalon?

**Comment by ihartu** [comment]
a #33-hoz kapcsolódik

**Comment by koch-mate** [comment]
A #33-at javitottam, igy akkor ezt is zarom.
