### ISSUE TITLE
Claudio

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#33]
nem jelölöm be a lakosságit, nem látom az exportot.

**Comment by koch-mate** [comment]
Ezt nekem szantad? Ha igen, kerlek magyarazd el, mert nem ertem.

**Comment by ihartu** [comment]
Igen, neked. Az adminban ha nem jelölöm be a "lakossági" kék négyzetet akkor nem látni az "exportot". A Zsoltnak bejelöltem csak az exportot, de nem látta. Csak akkor ha a lakossági is be volt jelölve.

**Comment by koch-mate** [comment]
Az "Osszes megrendelesek" menuben levo szuresre gondolsz? A narancssarga kapcsolot atallitottad zoldre a sor elejen, hogy be legyen kapcsolva az a szurofeltetel?

**Comment by ihartu** [comment]
nem. az adminisztrációban, ahol hozzárendelem a személyekhez a hozzáféréseket

**Comment by koch-mate** [comment]
Ja, megvan, koszi! Javitottam, most igy mukodik:
 - lakossagi joggal latod: Uj lakossagi rendeles felvetele, Lakossagi rendelesek (csak olvashato)
 - export joggal: Uj export rendeles, Export rendelesek (szerkesztheto), Export megrendelok kezelese
 - admin joggal: Oszes megrendeles (szerkesztheto)
