### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#34]
akinél nincs bejelölve az export megrendelés, az ne lássa az export szállítást

**Comment by koch-mate** [comment]
Ez a ketto nem fugg ossze, olyat tudok csinalni, hogy akkor lesz kulon export es kulon lakossagi szallitas, ok mindketten csak a megfelelo kategoriat lathatjak. Ez jo?

**Comment by ihartu** [comment]
Ha a "Szállítás" helyett lesz "Export szállítás" és "Lakossági szállítás" akkor szuper és az adminisztrációban külön kék kis négyzetekkel, hogy a megfelelő személyekhez lehessen hozzárendelni.

**Comment by koch-mate** [comment]
Ez a #23-as kapcsan megoldodik.
