### ISSUE TITLE
S:O:S!!! Lakossági megrendelések

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#36]
Ki fogadja el a lakossági megrendeléseket? Jelen pillanatban az akinek be van pipálva a lakossági ÉS az export megrendelések. 
Vagy a rendelés bevivő (csak a lakossági megrendeléseket lássa) vagy a telepvezető (gyártás) fogadhassa el a lakossági megrendeléseket.

**Comment by ihartu** [comment]
A lakossági rendelést felvevő személy láthassa, ha gyártásra vár, legyártva vagy szállításra vár. Tájékoztatásul.

**Comment by koch-mate** [comment]
Lett egy uj oldal, "Felvett megrendelesek listaja", ahol csak olvashato modon jelenik meg a lakossagi joguaknak az osszes lakossagi megrendeles.
