### ISSUE TITLE
Szallitasi adatok szerkeszthetosege teljesites utan

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#37]
A fizetési státusz módosítása lehetséges a zöld pipa után is. Ez nagyon jó!! Véletlenül vettem észre. Ez úgy működik, hogy ha ma én változtatom a dátumot akkor annak nyoma van és ha holnap valaki más átírja az én dátumomat akkor annak is nyoma van?ha igen, akkor ok és...
ugyan ez az opció kellene a szállításnál is, hogy a zöld pipa után lehessen módosítani a szállítólevél, számla, cmr, ekáer és fuvarozó számát, személyét. A "teljesítve" után csak az tudjon módosítani akinek van admin jogosultsága.

**Comment by ihartu** [comment]
Most lett tényleg aktuális a dolog. #166 és #233. Figyelmetlenségből a 233-hoz is, egy előzőleg már bevitt megrendeléshez tartozó adatokat vittem be. Ezért lenne jó ha lehetne utólag módosítani ezeket az adatokat amik nem befolyásolják a termelést. Illetve jó lenne ha jelezne, hogy a bevitt adat (számsor) már létezik. Pl. u.a. Ekáer szám vagy számlaszám ne szerepelhessen 2 helyen. Vagy ha igen akkor legalább kérdezzen rá, hogy tényleg ezekkel az adatokkal szeretném elmenteni?

**Comment by koch-mate** [comment]
Megcsinaltam, a Megrendelesek menu alatt az Osszes megrendeles es az Export megrendelesek kezelese menu alatt lehet utolag is modositani, a mar leszallitott mergeneles szallitasi adatain is. 

Az, hogy a beirt adatokat osszevesse a korabbiakkal, egy extra keres, ha fontos, kerlek nyiss rola egy uj ticketet, es adok ra ajanlatot.
