### ISSUE TITLE
FONTOS! Alapanyag felhasználás

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#38]
A példa a "Gyertyán" alapanyag. A pénteken bevitt rendeléshez kapcsolt alapanyag mennyiséget nem törli ha lefogyasztom a teljes mennyiséget (ID6, 8 és 30). 
A ma bevitt (utolsó próbaként) gyertyán mennyiség sem került levonásra! 
25,19m3 -t vittem be: ID6: 2,02 + ID8: 20,00 + ID30: 3,17 (15-ből).
De a következő alapanyag szükségletnél ott van az ID6: 2,02-vel (az ID8 is és az ID30-ból sem tűnt el 3,17) pedig az előző rendelésnél kifuttattam.

**Comment by koch-mate** [comment]
Javitva
