### ISSUE TITLE
teljes képernyő

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#39]
még mindig nem megfelelő a képernyő méret. a régi admin teljes képernyős (nem kell csúszkát használni), az újnál még lehetne szélesíteni.

**Comment by koch-mate** [comment]
Sokkal tobb lett az adat, es a szuresek/atlathatosag miatt nem is tudom nagyon osszehuzni. Most kiszelesitettem a kozepso ablakot maximalisra, csak egy nagyon vekony sav maradt mellette mindket oldalon, ami mar nem ad hozza erdemben, anelkul viszont csunya, hogy nincs szele. :)

Azt tudod meg csinalni, hogy ha jo a monitorod, es nem zavar a kisebb betu, akkor a Ctrl es a +, - billentyukkel tudod allitani a betumeretet. "Ctrl" + "-"-t nyomkodva le tudod csokkenteni ugy, hogy ne kelljen gorgetni. Visszaallni a "Ctrl" + "+" nyomkodasaval, vagy egy ugrassal a "Ctrl" + "0" lenyomasaval tudsz.
