### ISSUE TITLE
Konstansok

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#49]
A termékek nevei mellett szerepeljen a benne lévő fa mennyisége is:

Egyutas kaloda (kicsi): 1rűrm
Egyutas kaloda (keskeny): 1,24rűrm
Egyutas kaloda (normál): 1,65rűrm
Egyutas kaloda (nagy): 1,8rűrm
Visszaváltható kaloda (kicsi): 1rűrm
Visszaváltható kaloda (nagy): 2rűrm
Posch hálós: 2.1szűrm
Posch hálós, fóliázott: 2,1szűrm

**Comment by koch-mate** [comment]
Megcsinaltam, de a korabban adott atvaltasi tablazatotok alapjan, amit a programban is leellenoriztetek, a Posch nem 2,1, hanem 2,24 szort urmeterrel megy. Most melyik legyen?
