### ISSUE TITLE
Nyelv

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#50]
Miért nem magyar nyelvű a GitHub? Legyen magyar nyelvű.

**Comment by koch-mate** [comment]
A githubot nem en csinalom, csak egy ingyenes szolgaltatas, amit hasznalok, mert joval konnyebb itt osszegyujteni, kezelni a hibajelenteseket, mint emailben lenne. Ha a hasznalataval kapcsolatban kerdes van, szivesen segitek, de sajnos ez csak angol nyelven mukodik.
