### ISSUE TITLE
Lejárt határidejű, befizetetlen, teljesített megrendelések - Ft

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#72]
Kimutatás/áttekintés/Lejárt határidejű, befizetetlen, teljesített megrendelések - Ft:

Még mindig nem tudom itt értelmezni a kördiagramot.
Szerintem itt nincsenek határidők (legalább is a fizetéssel kapcsolatban). 
F: kifizetett megrendelések a tárgyévben: 0000Ft (amit jó lenne látni havi bontásban is)
NFHT: kifizetetlen, még nem kiszállított megrendelések: 0000Ft
Az FHT-t és az NF-et nem értem a lakossági kiszállításokkal kapcsolatban.
De most, hogy jobban megnézem, azt jelenti az FHT esetében, h mi késve szállítottuk le az ígért szállítási határidőhöz képest? ha igen, akkor jó.
Az NF pedig azt mutatja, h szállítási határidőn belül vagyunk még, de nincs még kiszállízva?
NF + NFHT = Leszállítandó megrendelések?

**Comment by koch-mate** [comment]
F + FHT legyen a teljes bevetelhez
megrendeles datuma helyett teljesites datuma szerint legyen.
"kifizetett" helyett "kiszalllitott"

**Comment by koch-mate** [comment]
legyen havi bontas is
