### ISSUE TITLE
Lezart gyartasok modositasa

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#75]
az ID392-es megrendelés ID497-es tételét véletlenül a bükk alapanyagból vettem le, a tölgy helyett.19,6m3.  Ezt én tudom korrigálni vagy téged kell megkérni, h kézi vezérléssel a bükk-be visszategyed és a tölgyből elvegyed? köszi

**Comment by ihartu** [comment]
Zsolttal egy kicsit még buheráltunk rajta. Mondta, h megtudjuk csinálni. De eddig nem ment.

**Comment by koch-mate** [comment]
par hete kerted, hogy ne jelenjen meg a gyartasra varo tetelek listajaban az, ahol mar minden le van gyartva. sajnos akkor nem jutott eszembe, hogy ez miert volt fontos, hat ezert :) 
lehet azt fogom csinalni, hogy admin joggal lehessen a lezart rendelesek teteleit is modositani, es akkor tudjatok majd utolag. ez jo?

**Comment by ihartu** [comment]
Nem. Azt beszéltük, h jelenjen meg de ne az első blokkban mert az zavaró, hogy a gyártásra váró ablakban először a legyártott megrendelések jönnek elő.
Ez az admin-os dolog jó lehet.
Ez úgy működne, hogy visszatudom varázsolni a bükköt hengeres alapanyagba és leveszem a tölgyből?
Mert akkor ez lenne az igazi.

**Comment by koch-mate** [comment]
Igen, ha kitorlod majd a felhasznalt bukkot, az visszamegy alapanyagba, es mas rendelesnel ujra fel lehet hasznalni.

**Comment by ihartu** [comment]
Ok. Értesíts, ha tudom módosítani. Köszi!
