### ISSUE TITLE
Kulso gyarto megrendelesekhez

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#8]
Nincs lehetőség megválasztani a megrendelés legyártásának a helyét (a régi adminban van rá mód és ez fontos). Van úgy, hogy nem Szentgálon csináltatom, hanem Nagykanizsán vagy Csömödér Stb.
De ezt lehessen módosítani is, mert előfordul, hogy nálunk nem megy, de máshol épp van erre alapanyag vagy késztermék. Vagy fordítva.

**Comment by koch-mate** [comment]
Ha nem ti gyartjatok, akkor nem is a ti keszletetekbol megy le a rendeles, es akkor nem is fogja senki a gyartas allapotat reszletesen kozolni, ugye?

**Comment by ihartu** [comment]
...ok, ok, de akkor ez a program nem használható az "idegen" termelésre. Erre akkor marad a régi admin?
