### ISSUE TITLE
többet vesz le az alapanyagból #2

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#80]
ráklikkelek a "részletek" gombra. megnyílik. ok. de nem tudok visszamenni. nincs hová klikkelni, hogy becsukjam. vagy vmit nem vettem észre?

az  ID484es megrendelésnél visszatettem "gyártás alatt"-ból "visszaigazolásra várva". Itt vettünk le próbából (pénteken) többet az alapanyagból (ID1340). De szerintem rosszul csináltam, mert előtte nem töröltem a mennyiséget a piros kukával. Így nem került vissza a felhasznált alapanyag a még felhasználásra váró alapanyaghoz. Hogy tudom ezt rendbe tenni?

**Comment by koch-mate** [comment]
Menj vissza a gyartas alatt statuszba, es torold, ami benne maradt.

**Comment by koch-mate** [comment]
Az, hogy ilyenkor magatol nem torli, az direkt van, mert ilyenkor lehet, hogy tenyleg legyartottatok mar valamit, ami be is van csomagolva, es nem egyertelmu, hogy azt at lehet tenni masik megrendelesre, igy ezt kezzel kell adminisztralni, amennyiben igen.

**Comment by ihartu** [comment]
Szuper, köszi. Jó ez így. Most már tudom mi a rendes sorrend.
