### ISSUE TITLE
Frissítés

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#83]
Megrendelés/Összes megrendelés:
Szűrők: 
Megrendelés dátuma: 2017 Szeptember.
Típus: Lakossági.
Frissítés.
Dátum szerint (növekvő sorrendben) megint csak a tiszta zöld sorok jönnek be először. Ok.
Ráklikkelek a "Megrendelés státuszára", bejönnek először a "feldolgozás alatt"-i megrendelések, utána alattuk az "elfogadva" megrendelések majd a teljesítettek. Ez így rendben is van. Ezt a sorrendet szerettem volna mert először mindig a "feldolgozás alatt"-i megrendelésekkel kell foglalkoznom.
Ráklikkelek az első sorban lévő "feldolgozás alatt"-i megrendelésre és elfogadom.
Tegyük fel, hogy van 4-5 elfogadásra váró megrendelés.
Az elfogadás után (szerintem) az lenne a logikus, hogy  vagy visszaugrik az elfogadásra váró megrendelésekhez vagy az éppen elfogadott megrendeléshez. Inkább az előző.
De nem.
Még az általam beállított "Megrendelési státusz"-hoz sem ugrik vissza. 
Mindent újra kezdhetek elölről. 
Ha csak így lehet megoldani, akkor legalább legyen a szűrőknél 1 gomb (lakosságinál és az exportnál is) ahol be tudom állítani, hogy milyen megrendeléseket szeretnék látni.

**Comment by koch-mate** [comment]
Ezt meg fogja oldani, ha lesz kulon csak elfogadasra varo megrendeles menu.
