### ISSUE TITLE
2018-as export rendelések + fuvar ár számítás

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#86]
![screenshot-2018-1-12 nemestrinus - uj megrendeles](https://user-images.githubusercontent.com/29250209/34874667-4f11ad8a-f79a-11e7-8aca-a5885537ec41.png)

Ezt nehezen fogom megfogalmazni.
Úgy kellene megcsinálni, hogy a végösszeg a beírt szállítási díj előtt legyen.
Nálunk mindenhol az ár tartalmazza a fuvarárat is. Így ha ügyesek vagyunk, azon is tudunk keresni pár eurót.
Tehát amikor beírom a tényleges szállítási díjat (legyen most €650) akkor a háttérben a program (ha akarja) levonja a végösszegből, tudva azt, h elment 45 rakott űrméter. Így a 650-et elossza 45-el (az 14,44) és ahol kell, ezt az adatot felhasználja. Az űrméter mellet lehet db is.
Ha már mindenképpen összekapcsoljuk, akkor ne hozzáadja hanem vonja le.
Remélem annyira érthető, hogy elkezdjünk róla beszélni.

**Comment by ihartu** [comment]
hú, ez nagyon durva!!!!
"elossza" ilyet, hogy lehet leírni. csak szégyenkezni tudok ezen. nem "elosztja"??
nagyon gáz...

**Comment by koch-mate** [comment]
Teljes ar mar tartalmazza a fuvart:
 - vegosszeg fix
 - fa ara = vegosszeg - fuvarar
Csak EXPORT eseten!!!
