### ISSUE TITLE
Lakossági megrendelés

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#87]
Jelenleg 1-Másfél hónapra (gyártás + kiszállítás) veszünk fel megrendelést. A rendelés felvételnél 14 nap az ígért teljesítés. Az ígért teljesítés szerintünk a szállítást is magába foglalja, ezért nem 14 hanem 28 nappal kellene számolnia. Alaphelyzetben. DE:
Jelen pillanatban ez sem elég, legalább másfél hónapra van szükségünk. A konstansok között jó lenne ha át tudnánk állítani.

**Comment by koch-mate** [comment]
Igen, itt volt egy hiba, a gyartasi idot nem szamolta bele, csak a szallitasit. Ezt javitottam, plusz atirtam a gyartasi idot 1 honapra. Igy most 1,5 honapot szamol alapbol.
