### ISSUE TITLE
Hiba, ha a belepes utan a Felhasznalok oldalra iranyit a rendszer

### ISSUE THREAD

**Issue by koch-mate** [koch-mate/nemestrinus#9]
A $_POST kulcsa ugyanaz, javitani kene a belepes utani atiranyitast rendes redirectre.

**Comment by ihartu** [comment]
ezt nem nekem szántad szerintem.

**Comment by koch-mate** [comment]
Nem, ide sajat magamnak is veszek fel emlekeztetoket, ha valamit nem ti nyitottatok, azzal nem kell foglalkoznotok
