### ISSUE TITLE
Export megrendelések

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#90]
ID507.
Töröltem egy 1db-os tételt. Ok.
Szerettem volna bevinni (zöld "új tétel" gomb segítségével) egy tételsort (2x is) de a "mentés" után nem látszik semmi változás. 
Remélem az alapanyagból sem veszi le!

**Comment by koch-mate** [comment]
Ez is misztikus. Kiprobaltam, nekem ment, hozzaadtam, majd le is toroltem egy tetelt az 507-es rendeleshez. Mindenesetre bekapcsoltam, hogy a szerveren gyujtse a hibauzeneteket, ha megint van ilyen hiba, szolj, es akkor talan onnan kiderul valami.
