### ISSUE TITLE
ID628 Berki Szilvia

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#91]
Nem látni sem a legyártott, sem pedig a gyártás alatt lévő megrendelések között. Le van gyártva, ott a "zöld" pipa, de a homok óra nem változott át teherautóvá.

**Comment by koch-mate** [comment]
Nem ertem mi lehetett itt a gond. Kijavitottam ennel az egy tetelnel, de ennek automatikusan kell mukodnie, es eddig ugy tunt, mukodik is. En most tobbszor kiprobaltam, es jo volt, ha ujra elojon a hiba, kerlek szolj, es valahogy ki kene talalni, hogy mi lehet az ok, mivel fugghet ossze.

**Comment by koch-mate** [comment]
Azt meg beletettem, hogy adminisztratorkent az osszes megrendeles oldalon mindenkepp at tudd tenni mas szallitasi allapotba. Erre amiatt is szukseg van, mert ha pl van egy rendeles, es annak 4 tetele kozul 3 legyartott, 1 meg visszaigazolasra var, akkor azt meg lehet szerkeszteni es akar torolni is. Ha torlod, akkor utana minden megmaradt tetel legyartott lesz, es ha nem viszel fel uj tetelt, akkor,  elvileg kesz is a gyartas, viszont ilyenkor nem all at magatol - neked kell kezzel szallitasra var allapotura allitani.
