### ISSUE TITLE
30,79

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#94]
![screenshot-2018-2-12 nemestrinus - osszes megrendeles](https://user-images.githubusercontent.com/29250209/36088780-d88c7288-0fd8-11e8-92f3-fc10ed5710a1.png)

**Comment by koch-mate** [comment]
A pontos ertek a mostani konstansok alapjan 1.39958, ami kerekitve 1.4-kent jelenik meg. A program viszont mindig a pontos ertekkel szamol a hatterben, es ezert lesz a 22 x 1.39958 = 30.79076.
