### ISSUE TITLE
Export megrendelők - #26 Molino ... Gomiero Ugo

### ISSUE THREAD

**Issue by ihartu** [koch-mate/nemestrinus#98]
módosítottam a címet 2x, de nem rögzíti. talán mert túl hosszú??

**Comment by ihartu** [comment]
a PAVAN COMBUSTIBILI-nél is

**Comment by ihartu** [comment]
szerintem a többinél is azért (is) hiányos. megvárom a megoldásod. aztán folytatom.

**Comment by koch-mate** [comment]
adatbazis mezo tul rovid

**Comment by koch-mate** [comment]
javitva
